const sportsAcademies = [
    {
      city: "hyderabad",
      sport:"cricket",
      name: "Daniel Cricket Academy",
      location: "hyderabad",
      image: "https://playo-activities.gumlet.io/DANIELSCRICKETACADEMY/DanielsCricketAcademycover1502371285385.jpg?q=40",
      timing: " 6 AM - 8 AM, 4 PM - 8 PM ",
      id: 1,
      image2: "https://playo-activities.gumlet.io/DANIELSCRICKETACADEMY/DanielsCricketAcademyIMG0.jpg",
      overview: "DANIEL KANAPARTHI, a Level II certified Coach from England and Wales Cricket Board (ECB, United Kingdom), is always passionate for his all time favourite dream game “CRICKET”, has opted it as a career and opened his own Academy - DANIEL’S CRICKET ACADEMY in Hyderabad.Daniel is also an active member of England and Wales Cricket Coaches Association. Having great passion for cricket Daniel has taken up a challenging responsibility of grooming the upcoming players for INDIA.DCA is not just a cricket coaching academy, it has grown as a team, a family with bonding among, students, coaches and parents.",
      goals: " To maintain quality coaching standards and contribute best cricket players to represent INDIA.Identifying the talented boys having passion for cricket and ensuring wide range of support, encouragement and guidance to achieve the goal.To make coaching facilities available and accessible to the talented boys from towns and villages of Telangana and Andhra Pradesh",
      services: "Coaching starts at 5:45 a.m. continues till 8:00 a.m. and in the evening starts at 4:00 p.m. continues till 8:00 p.m.Friendly matches are conducted during the weekends.Fitness program - to make the boys both physically and mentally strong. Special emphasis on fielding, bowling and batting.Giving awareness about international standards and rules.Matches are organized under flood lights with 20-20 format on Saturdays and Sundays for children to get them used to difference match situations/conditions."
    },
    {
      city: "hyderabad",
      name: "SVM Bowling Alley Gachibowli",
      sport:"bowling",
      location: "36/A, Sai Tirumala Platinum Building, Old Mumbai Hwy, Telecom Nagar Extension",
      image: "https://playo-activities.gumlet.io/SVMBOWLINGALLEY/SVMBowlingAlleycover.jpg?q=40",
      timing: "All Days | 10 AM - 10 PM",
      image2: "https://playo-activities.gumlet.io/SVMBOWLINGALLEY/SVMBowlingAlleyGachibowliIMG2.jpg",
      overview: "Come Play bowling at SVM Bowling Alley Gachibowli with these amazing offers for all 7 days a week !!",
      id: 2,
      goals: "",
      services: "Exclusive offers only on Playo. From (Monday - Thursday) 10 AM - 1 PM - Rs 99/Game 1 PM - 5 PM - Rs 149/Game 5 PM - 10 PM - Rs 199/Game From (Friday - Sunday) 10 AM - 1 PM - Rs 180/Game 1 PM - 10 PM - Rs 260/Game But hey, Buy 9 Games or more on the weekends and you either get a pitcher of BEER free or 2 games free."
    },
    {
      city: "hyderabad",
      name: "CHETAN ANAND BADMINTON ACADEMY",
      location: "Madhapur",
      sport:"badminton",
      image: "https://playo-activities.gumlet.io/CHETANANANDBADMINTONACADEMY/ChetanAnandBadmintonAcademycover1502367127642.jpg?q=40",
      timing: "Morning 5 AM - 7 AM, Evening 4 PM - 6 PM",
      id: 3,
      image2: "https://playo-activities.gumlet.io/CHETANANANDBADMINTONACADEMY/ChetanAnandBadmintonAcademyIMG1.jpg",
      overview: "Chetan Anand Badminton Academy’s main aim is to provide a platform for the young talented players to not only learn the nuances of the sport but also to develop into world-class players and achieve their goals. All of this is done through world-class coaching, state-of-the-art facilities, and the right exposure and support.",
      goals: "",
      services: "Morning sessions from 5 AM - 7 AM. Evening sessions from 4 PM - 6 PM. To Enroll, Please contact the provided phone number."
    },
    {
      city: "hyderabad",
      name: "PRAXIS SWIMMING",
      location: "Narayanguda",
      sport:"swimming",
      image: "https://playo-activities.gumlet.io/PRAXISSWIMMING/PraxisSwimmingcover1502369476989.jpg?q=40",
      timing: "6 AM - 10 AM, 4 PM - 9 PM (Tuesday - Sunday)",
      id: 4,
      image2: "https://playo-activities.gumlet.io/PRAXISSWIMMING/PraxisSwimmingIMG2.jpg",
      overview: "Welcome to Praxis Swimming, the most technologically advanced swimming pool in Hyderabad! Our venue has a temperature controlled environment making swimming a pleasure. Our venue also has a UV sterilization process which ensures that the water is hygienic.",
      goals: "",
      services: "Includes swimming coaching and many other fitness activities like Gym, Yoga and Aerobics."
    },
    {
      city: "hyderabad",
      name: "INSPORTS CRICKET ACADEMY",
      location: "Banjara Hills",
      sport:"cricket",

      image: "https://playo-activities.gumlet.io/INSPORTSCRICKETACADEMY/InsportsCricketAcademycover1502366698506.jpg?q=40",
      timing: "6 AM - 8 AM, 4 PM - 8 PM",
      id: 5,
      image2: "https://playo-activities.gumlet.io/INSPORTSCRICKETACADEMY/InsportsCricketAcademyIMG0.jpg",
      overview: "Welcome to Insports Cricket Academy! We believe in making a positive contribution to the game of cricket by providing quality training and creating opportunities for young and aspiring cricketers.",
      goals: "",
      services: "Coaching, Safety equipment, Tournaments."
    },
    {
      city: "hyderabad",
      name: "ST. JOHNS CRICKET ACADEMY",
      sport:"cricket",
      location: "East Marredpally",
      timing: "Morning & Evening sessions",
      id: 6,
      overview: "St. John’s cricket academy was established in the year 1987 with a vision to provide quality infrastructure and coaching in cricket. The academy has produced many players who have gone on to represent the country at the international and national levels.",
      goals: "",
      services: "Coaching in batting, bowling, and fielding techniques. Indoor and outdoor practice facilities."
    },
    {
        city: "delhi",
        name: "SEHWAG CRICKET ACADEMY",
        sport:"cricket",
        location: "X-12, Hauz Khas Road, Hauz Khas Main Market, New Delhi, Delhi 110016",
        image: "https://playo-activities.gumlet.io/SEHWAGCRICKETACADEMY/SehwagCricketAcademycover1509335108795.jpg?q=40",
        timing: "Morning and Evening Session",
        image2: "https://playo-activities.gumlet.io/SEHWAGCRICKETACADEMY/SehwagCricketAcademyIMG0.PNG",
        overview: "The foundation of the Sehwag Cricket Academy was laid by Virender Sehwag with the sole aim of providing quality cricket training, world-class cricketing infrastructure, and opportunity to learn from experts in the field of cricket through a fun and innovative environment. The flagship cricket academy was founded in 23-acre eco-friendly campus at Jhajjar, on the outskirts of Gurgaon, Haryana in the year 2011, with an emphasis to provide students with best-in-class cricket facilities and training. This all-year-round academy integrates the best in cricketing techniques, technology, and coaches to develop a World-Class Cricketer of Tomorrow. For the overall development of the young cricketer, strength improvement through other games – swimming, tennis, football – mini tournaments, and sessions with specialists are organised, based on the ability, age group, and expertise level of the players.",
        goals: "",
        services: "",
        infrastructure: "",
        address: "X-12, Hauz Khas Road, Hauz Khas Main Market, New Delhi, Delhi 110016",
        id: 11
      },
      {
        city: "delhi",
        name: "MADAN LAL CRICKET ACADEMY",
        sport:"cricket",
        location: "DDA Siri Fort Sports Complex, August Kranti Marg, Khelgaon, Behind Siri Fort Auditorium, New Delhi, Delhi 110049",
        image: "https://playo-activities.gumlet.io/GYANTICRICKETCOACHING/GyantiCricketCoachingcover1509432145244.jpg?q=40",
        timing: "Morning and Evening session",
        image2: "https://playo-activities.gumlet.io/MADANLALCRICKETACADEMY/MadanLalCricketAcademyIMG0.PNG",
        overview: "Madan Lal Cricket Academy managed by Matchcraft Sports Management. Madanlal Academy brings Cricket and Education together in India with Amenity School of Education adanlal Academy create talent, nurture them with regressive training sessions and make them stand out leaders. We are fortunate to have with us a highly respected and brilliant coach in the form of Mr. Madan Lal former Indian Test Cricketer. Individual coaching sessions can be arranged with Madan Lal one to one coaching specifically for the individual. We intend picking up a few of the boys from schools and hopefully, the ‘best’ and ‘most talented’ can possibly represent the country in the under 19 category",
        goals: "",
        services: "",
        infrastructure: "",
        address: "DDA Siri Fort Sports Complex, August Kranti Marg, Khelgaon, Behind Siri Fort Auditorium, New Delhi, Delhi 110049",
        id: 12
      },
      {
        city: "delhi",
        name: "HARBEER CRICKET ACADEMY",
        sport:"cricket",
        location: "Opp.Japanese Park, Sector 9, Rohini west, Delhi, 110085",
        image: "https://playo-activities.gumlet.io/HARBEERCRICKETACADEMY/HarbeerCricketAcademycover1509431328272.jpg?q=40",
        timing: "Morning and Evening session",
        image2: "",
        overview: "Neo Convent School functions with an exalted aim of providing excellent education opportunities to the students irrespective of caste, creed or religion. Its motto “Knowledge Thy Wealth” explains all that the school stands for. The initiative to further the cause of education through this school was taken by “Neo Gursikh Education Society”. The aforesaid registered Society with the Managing Committee looks after and controls the activities of the school. The School was recognized by Delhi Administration and by M.C.D in 1976. Upgradation for Senior Secondary stage was granted by Delhi Administration in 1992. The school is affiliated with CBSE up to Senior Secondary level. Currently, affiliation is granted till 2018. The aim of the school is to create an academic and physical environment of a nature, which helps the children to become ideal members of society develop skills and knowledge which is the envy of all and lastly, have a disciplined character embodied with the spiritual values of our Gurus.",
        goals: "",
        services: "",
        image3: "https://playo-activities.gumlet.io/EXTRATIMEFOOTBALLACADEMY/ExtraTimeFootballAcademyIMG0.PNG",
        infrastructure: "",
        address: "Opp.Japanese Park, Sector 9, Rohini west, Delhi, 110085",
        id: 13
      },
      {
        city: "delhi",
        name: "EXTRA TIME FOOTBALL ACADEMY",
        sport:"football",
        location: "Vasant Vatika, Opposite DPS Vasant Kunj, New Delhi, Delhi 110070",
        image: "https://playo-activities.gumlet.io/EXTRATIMEFOOTBALLACADEMY/ExtraTimeFootballAcademycover1509432907532.jpg?q=40",
        timing: "Morning and Evening session",
        image2: "https://playo-activities.gumlet.io/EXTRATIMEFOOTBALLACADEMY/ExtraTimeFootballAcademyIMG0.PNG",
        overview: "ExtraTime Football Academy will be providing you with a chance to improve your footballing skills and help you learn new techniques and tactics.",
        goals: "",
        services: "",
        infrastructure: "",
        address: "Vasant Vatika, Opposite DPS Vasant Kunj, New Delhi, Delhi 110070",
        id: 14
      },
      {
        city: "delhi",
        name: "FCBESCOLA FOOTBALL SCHOOL - WEST DELHI",
        sport:"football",
        location: "Shivaji College Sports Complex iOS Maidan, Shivaji Enclave, Tagore Garden Extension, New Delhi, Delhi 110018",
        image: "https://playo-activities.gumlet.io/FCBESCOLAFOOTBALLSCHOOL-WESTDELHI/FCBEscolaFootballSchoolWestDelhicover1509433782873.jpg?q=40",
        timing: "Morning and Evening session",
        image2: "https://playo-activities.gumlet.io/FCBESCOLAFOOTBALLSCHOOL-WESTDELHI/FCBEscolaFootballSchoolWestDelhiIMG0.PNG",
        overview: "Conscient Football is a grassroots development initiative undertaken by the Conscient Group with the Heritage Schools network in Delhi NCR; the latter being a part of its ventures in the education sector, as an extension of its wider portfolio. Conscient Football is dedicated to raising the bar in football programming at the grassroots level by reaching out to children across Delhi NCR in the initial years, and its exclusive collaboration with one of the world's greatest football clubs- FC Barcelona is one of the various steps taken in that direction. The greater aim is to establish a nationwide footprint with its football development activities over the next few years whilst establishing the foundation in terms of a feeder program for FCBEscola- the world-class football school imparting high-class football education catering to the best players found within its programs. The FCBEscola which will be at the apex of CF's football development pyramid, and will be run by Technical Director from FC Barcelona and will aim to put forth the best football players in the country who aspire to pursue the game professionally at the elite level.",
        goals: "Make Indian youth achieve world football standards Create centres of excellence in football Make students and parents aware of the need for physical exercise and enjoying a good game.",
        services: "",
        infrastructure: "",
        address: "Shivaji College Sports Complex iOS Maidan, Shivaji Enclave, Tagore Garden Extension, New Delhi, Delhi 110018",
        id: 15
      },
      {
        city: "delhi",
        name: "PHOENIX FOOTBALL ACADEMY",
        sport:"football",
        location: "DDA Sports Complex, Muni Maya Ram Jain Marg, Pitampura, Delhi, 110034",
        image: "https://playo-activities.gumlet.io/PHOENIXFOOTBALLACADEMY/PhoenixFootballAcademycover1509435605936.jpg?q=40",
        timing: "Morning and Evening session",
        image2: "https://playo-activities.gumlet.io/PHOENIXFOOTBALLACADEMY/PhoenixFootballAcademyIMG0.PNG",
        overview: "Phoenix Sports Academy is an upcoming dynamic sports management group run by passionate professionals. Our motive is to establish Sports as an integral part of youth development at all stages. Phoenix Sports Academy is a football academy providing high-quality football coaching courses for boys and girls in Pitampura, Rohini, Ashok Vihar, Lawrence Road, Delhi, and nearby areas. Established over five years we are proud to be known for helping children become more proficient in the game of soccer in a fun and friendly environment. We offer structured and organized football coaching sessions led by experienced coaches. Whether your kids are just looking for a fun time or want to develop their football interests and skills further, we provide a platform for your children to enjoy the game whilst receiving expert football coaching.",
        goals: "",
        services: "",
        infrastructure: "",
        address: "DDA Sports Complex, Muni Maya Ram Jain Marg, Pitampura, Delhi, 110034",
        id: 16
      },
      {
        city: "pune",
        name: "TWENTY2YARDS CRICKET ACADEMY",
        sport:"cricket",
        image:"https://playo-activities.gumlet.io/PHOENIXFOOTBALLACADEMY/PhoenixFootballAcademyIMG0.PNG",
        location: "R.No. 52/C, Dagade-Patil Nagar, Opp. Pinnacle Brookside, Mumbai-Bangalore Bypass Highway, Bavdhan Khurd, Pune, Maharashtra 411021",
        timing: "Morning and evening session",
        overview: "Twenty2yards is a specialized cricket academy...",
        address: "R.No. 52/C, Dagade-Patil Nagar, Opp. Pinnacle Brookside, Mumbai-Bangalore Bypass Highway, Bavdhan Khurd, Pune, Maharashtra 411021",
        id: 17
      },
      {
        city: "pune",
        name: "ARYANS CRICKET ACADEMY",
        sport:"cricket",
        image: "https://playo-activities.gumlet.io/MADANLALCRICKETACADEMY/MadanLalCricketAcademyIMG0.PNG",
        location: "Mulberry Gardens, Opp Laxmi Lawns, Magarpatta City, Hadapsar, Pune, Maharashtra 411028",
        timing: "Morning and evening session",
        overview: "At Aryans Cricket Academy, we have been coaching budding cricketers...",
        address: "",
        id: 18
      },
      {
        city: "pune",
        image: "https://playo-activities.gumlet.io/DANIELSCRICKETACADEMY/DanielsCricketAcademyIMG0.jpg",
        name: "SPORTS GALAXY TILEKAR SPORTS ACADEMY",
        sport:"cricket",
        location: "Mulberry Gardens, Opp Laxmi Lawns, Magarpatta City, Hadapsar, Pune, Maharashtra 411028",
        timing: "Morning and evening session",
        overview: "From the passion of sports 'Sports Galaxy' has emerge and established in 2015...",
        address: "",
        id: 19
      },
      {
        city: "pune",
        name: "PYC HINDU GYMKHANA",
        sport:"cricket",
        image: "https://playo-activities.gumlet.io/DANIELSCRICKETACADEMY/DanielsCricketAcademyIMG0.jpg",
        location: "CTS No. 766, F.P. No. 244, Bhandarkar Road, Pune, Maharashtra 411004",
        timing: "Morning and evening session",
        overview: "It all started in the year 1900, when a few young and enthusiastic cricketers formed ‘Poona Young Cricketers’ Hindu Gymkhana’...",
        address: "",
        id: 20
      },
      {
        city: "pune",
        sport:"cricket",
        name: "SANJAY SPORTS ACADEMY",
        location: "19/1b/1, Near Hotel Rajwada, Baner Road, Someshwarwadi, Pune, Maharashtra 411008",
        timing: "Morning and Evening session",
        overview: "The Life Sports is one of the leading Sports Academies in Pune...",
        address: "",
        id: 21
      },
      {
        city: "pune",
        name: "SILVER SPORTS CLUB",
        sport:"cricket",
        image: "https://playo-activities.gumlet.io/DANIELSCRICKETACADEMY/DanielsCricketAcademyIMG0.jpg",
        location: "165/1, 166/5, Near by Mumbai-Bangalore Highway, Behind Vedanta Society, Wakad, Shankar Kalat Nagar, Wakad, Pune, Maharashtra 411057",
        timing: "Morning and evening session",
        overview: "Silver Club came into existence to develop sports and games in India...",
        address: "",
        id: 22
      },
      {
        city: "mumbai",
        name: "SANJEEVANI CRICKET ACADEMY",
        location: "Bandra East",
        sport:"cricket",
        image: "https://playo-activities.gumlet.io/SANJEEVANICRICKETACADEMY/SanjeevaniCricketAcademycover1508259425818.jpg?q=40",
        timing: "Morning session",
        overview: "Sanjeevani Cricket Academy is a premier cricket academy located in Bandra East, Mumbai...",
        address: "Bandra East",
        id: 23
      },
      {
        city: "mumbai",
        name: "DHAWAN CRICKET ACADEMY",
        sport:"cricket",
        image: "https://playo-activities.gumlet.io/MADANLALCRICKETACADEMY/MadanLalCricketAcademyIMG0.PNG",
        location: "Pali Hill, Bandra West, Mumbai, Maharashtra 400050",
        timing: "Morning and evening session",
        overview: "Dhawan Cricket Academy is one of the well-known cricket academies in Mumbai...",
        address: "Pali Hill, Bandra West, Mumbai, Maharashtra 400050",
        id: 24
      },
      {
        city: "mumbai",
        sport:"cricket",
        image: "https://playo-activities.gumlet.io/DANIELSCRICKETACADEMY/DanielsCricketAcademyIMG0.jpg",
        name: "BHATKAR CRICKET ACADEMY",
        location: "Khalsa College, Guru Nanak Khalsa College, Mumbai, Maharashtra 400019",
        timing: "Morning and evening session",
        overview: "Bhatkar Cricket Academy is a popular cricket training center in Mumbai...",
        address: "Khalsa College, Guru Nanak Khalsa College, Mumbai, Maharashtra 400019",
        id: 25
      },
      {
        city: "mumbai",
        name: "Vengsarkar Cricket Academy",
        sport:"cricket",
        image: "https://playo-activities.gumlet.io/MADANLALCRICKETACADEMY/MadanLalCricketAcademyIMG0.PNG",
        image: "https://playo-activities.gumlet.io/CALCUTTACRICKETACADEMY/CalcuttaCricketAcademyIMG0.PNG",
        location: "DLH Junction, CTS No. 911 & 912, SV Road, Goregaon West, Mumbai, Maharashtra 400062",
        timing: "Morning and evening session",
        overview: "Vengsarkar Cricket Academy is a renowned cricket coaching center in Mumbai...",
        address: "DLH Junction, CTS No. 911 & 912, SV Road, Goregaon West, Mumbai, Maharashtra 400062",
        id: 26
      },
      {
        city: "mumbai",
        name: "Andheri Cricket Academy",
        sport:"cricket",
        image: "https://playo-activities.gumlet.io/CALCUTTACRICKETACADEMY/CalcuttaCricketAcademyIMG0.PNG",
        location: "Veera Desai Road, Andheri West, Mumbai, Maharashtra 400058",
        timing: "Morning and evening session",
        overview: "Andheri Cricket Academy is a popular cricket training academy in Mumbai...",
        address: "Veera Desai Road, Andheri West, Mumbai, Maharashtra 400058",
        id: 27
      },
      {
        city: "mumbai",
        name: "Global Cricket School",
        sport:"cricket",
        location: "Gurukul Rd, Malad East, Mumbai, Maharashtra 400097",
        timing: "Morning and evening session",
        image: "https://playo-activities.gumlet.io/FOOTBALLTOURNAMENT/FootballTournamentIMG0.jpg",
        overview: "Global Cricket School is a leading cricket academy in Mumbai...",
        address: "Gurukul Rd, Malad East, Mumbai, Maharashtra 400097",
        id: 28
      },
      {
        city: "kolkata",
        name: "FOOTBALL TOURNAMENT",
        sport:"football",
        location: "Indian Statistical Institute, 205 B.T. Road, Kolkata, West Bengal, India",
        image: "https://playo-activities.gumlet.io/FOOTBALLTOURNAMENT/FootballTournamentcover.PNG?q=40",
        timing: "11th March-19th March, 2017 | 9:00 A.M. - 7:00 P.M.",
        image2: "https://playo-activities.gumlet.io/FOOTBALLTOURNAMENT/FootballTournamentIMG0.jpg",
        overview: "We are pleased to introduce our organization Ocean Swimming Academy (since 2010). We create modern, innovative and inspirational pools. Over 200 pools that will take your breath away, you can be rest assured that when you work with us, you are working with the best people in the pool business. In fact we don't even think it's a business anymore. Each aquatic infrastructure we build is a true inspiration. After all it is a part of your home and reflects \"you,\" literally.We own a dedicated group of experts in the field of Swimming Education and Aquatic Infrastructures. Which offer services in design and Construction in the field of management, maintenance and safety. We are associated with number of educational institutions and built Olympic and Semi Olympic Pools of International Standards followed by leisure pools For fitness training and for recreation purposes.Our foundation is committed for providing state of the art design to the best satisfaction of our clients. All our projects were well appreciated by leading architects and general public wherein we have incorporated all the state of the art technologies in the design and construction of swimming pools and other Aquatic Infrastructures. We follow various International standards like, FINA for competitive Pool design and NSPF, SPATA, APSP,",
        goals: "",
        services: "",
        infrastructure: "",
        address: "",
        id: 29
      },
      {
        city: "kolkata",
        name: "CALCUTTA CRICKET ACADEMY",
        sport:"cricket",
        location: "Southern Ave, Lake Gardens, Vivekananda Park (est) Ground, Hemanta Mukherjee Sarani, lake Terrace, Ballygunge, Kolkata, West Bengal 700029",
        image: "https://playo-activities.gumlet.io/GULLYCRICKET/GullyCricketcover.PNG?q=40",
        timing: "Morning and Evening session",
        image2: "https://playo-activities.gumlet.io/CALCUTTACRICKETACADEMY/CalcuttaCricketAcademyIMG0.PNG",
        overview: "It all began with the vision of Abdul Masood, a former First Class cricketer and qualified cricket coach from the United Kingdom and India, who is additionally, a qualified Advocate at the Hon’ble High Court at Calcutta, of establishing a Cricket Academy. He dreamed of a state of the art facility, that would provide high-performance cricket coaching, to not only cricketers from Bengal, but also to those of other states and from other nations as well.  He has been joined in this venture by Wing Commander Arijit Ghosh (Retd) and Mr Probal Dutta, both former Ranji Trophy Cricketers and Level B Coach from the National Cricket Academy of the BCCI, to impart structured learning to young, aspiring cricketers. Together, they have worked diligently at the idea and today, Masood’s vision is a reality.  Calcutta Cricket Academy (CCA) provides personalized quality coaching in different age groups and experience levels. We run Weekend (Morning & Afternoon) and Thursday (Morning) coaching sessions throughout the year. These coaching programmes are tailor-made for junior cricketers from schools and clubs. Our well-researched training curriculum is backed up by the expertise of our friendly and approachable coaches and staff, who ensure that every child enjoys his cricket while learning the basics correctly and takes home a positive learning experience. This is our USP at CCA.  For advanced cricketers with more specialized needs, we have special one on one, or group coaching sessions with our BCCI NCA Level B coaches. We also have highly qualified visiting and guest coaches and strength and fitness conditioners, conducting fitness sessions for our children, periodically.  We run specialized cricket camps during school holidays where young cricketers can spend the day at the Academy with our coaches, training and developing their skills and fitness.",
        goals: "",
        services: "",
        infrastructure: "",
        address: "",
        id: 30
      }   
  ];

  export default sportsAcademies;